### ISSUE TITLE
[Feature] Constructing links INTO New Relic

### ISSUE THREAD

**Issue by skyzyx** [newrelic/newrelic-client-go#632] opened 2021-01-20 19:33 UTC
### Feature Description

The links for New Relic One look something like this:

```plain
https://one.newrelic.com/launcher/nrai.launcher?pane={base64}&sidebars[0]={base64}&platform[accountId]={account}
```

…where `{base64}` is a Base64-encoded JSON string with keys/values.

My feature request is to provide a helper to make it easier to construct these deep-links into New Relic One. If any values are enums, then to use enums in Golang so that it's harder to do things incorrectly.

### Describe Alternatives

I had started writing some code to construct these manually, but I don't know what all of the possible values are for the keys inside the Base64-encoded JSON strings. Probably not the end of the world, though.

**Comment by ctrombley** [comment] 2021-01-21 15:52
Hey @skyzyx , we reecently put an item on the backlog to allow _decoding_ these URLs from the CLI (newrelic/newrelic-cli#623).  This would be a nice complement to that functionaliity.

We will look to add this to the CLI as well.  We'll make sure to allow for programmatic use as well.   I'll move this FR over to the CLI repo.

**Comment by ctrombley** [comment] 2021-01-21 16:05
Duplicate of newrelic/newrelic-cli#634

**Closed by ctrombley** 2021-01-21 16:05 UTC
