### ISSUE TITLE
EpochTime UnmarshalJSON Error

### ISSUE THREAD

**Issue by diabeticMike** [newrelic/newrelic-client-go#992] opened 2023-02-24 15:13 UTC
### Description
UnmarhsalJSON method of `EpochTime` struct return an error in case we unmarshal an empty object

### Go Version
go version go1.19.5 darwin/amd64

### Current behavior
When I try to call UnmarshalJSON method of `EpochTime` struct's object I retrieve the next error
<img width="413" alt="Screenshot 2023-02-24 at 17 03 58" src="https://user-images.githubusercontent.com/23147241/221211893-16120bd6-99f7-4125-989b-9fc61b28449c.png">

### Expected behavior
Everything needs to be successfully unmarshaled

### Steps To Reproduce
1. As `EpochTime` struct declared in internal package we can't access it but we are going to access it via entities.DashboardEntity object (it has a field of `EpochTime` type `dashboard.NRDBQuery.Metadata.TimeWindow.Begin`)
2. First I marshal empty object to json
3. Then I unmarshal it back
4. Retrieve the error
5. Gist here https://gist.github.com/diabeticMike/d3abfd5b98b6c70b900cace344424442

### Debug Output (if applicable)
`strconv.ParseInt: parsing "-62135596800,": invalid syntax`

### Additional Context
As i saw there is even no unit tests for MarshalJSON func - i suppose thats the main reason
<img width="460" alt="Screenshot 2023-02-24 at 17 27 03" src="https://user-images.githubusercontent.com/23147241/221218054-7db936a3-f379-41f5-9518-27134e1ef04d.png">

**Comment by kidk** [comment] 2023-02-27 10:01
Thanks @diabeticMike for detailed ticket and reproducible case

This seems to be a known go issue and expected behaviour: https://github.com/golang/protobuf/issues/710 

I will double check with team to see if there's something we can do about this. 

If I can ask, what are you trying to do with the above? Or what's the use-case? Are you getting this error when talking to our API?

**Comment by diabeticMike** [comment] 2023-02-27 10:52
Hi @kidk , thanks for replying, the case is when I retrieve a list of dashboards then marshal them to JSON and then unmarshal back to the same struct - so EpochTime object is empty in the moment of marshaling but when i unmarshal i get an error

At this moment i created a fix for my case but test cases that are present are failing, so i'm trying to be backward compatible.
Also as i said you don't have any unit tests for MarshalJSON method.

**Comment by diabeticMike** [comment] 2023-02-27 13:03
I spent a few days digging into the problem and the last thing I want to propose (in case it is an emergency case) is this 
https://gist.github.com/diabeticMike/6c27c4128a4f2d06bdcf449bc000c444
Ping me again and in case you are ok to go with it - i'll make PR

**Comment by kidk** [comment] 2023-03-03 10:35
I've asked the team to review your PR @diabeticMike Thanks for making the change.

**Comment by sanderblue** [comment] 2023-03-13 15:40
Merged and released. Thanks @diabeticMike

**Closed by sanderblue** 2023-03-13 15:40 UTC
