### ISSUE TITLE
Getting JSON Unmarshal Errors from TF Plan using NR Provider

### ISSUE THREAD

**Issue by MAN98** [newrelic/newrelic-client-go#612] opened 2021-01-13 19:19 UTC
### Description
I am getting some weird errors when I run my CI build which executes a Terraform Plan against my code that uses v 2.7.1 of the NR Provider. This started happening today only and I did not have any errors with my CI build before this.

### Go Version
Not sure what the NR Provider uses for Go version

### Current behavior
TF Plan fails with Go related errors

### Expected behavior
No errors with JSON marshaling

### Steps To Reproduce
1. tf plan on terraform code using NR Provider

### Debug Output (if applicable)

Error: json: cannot unmarshal number into Go struct field entitySearchResponse.data.actor of type nrtime.Minutes
--
1349 |  
1350 | on modules/synth_script_api/main.tf line 48, in data "newrelic_entity" "entity":
1351 | 48: data "newrelic_entity" "entity" {
1352 |  
1353 |  
1354 |  
1355 | Error: json: cannot unmarshal number into Go struct field entitySearchResponse.data.actor of type nrtime.Minutes
1356 |  
1357 | on modules/synth_script_api/main.tf line 48, in data "newrelic_entity" "entity":
1358 | 48: data "newrelic_entity" "entity" {
1359 |  
1360 |  
1361 |  
1362 | Error: Service Exception: EntitySearchService.API.Error Server Error (504)
1363 |  
1364 | on modules/synth_script_api/main.tf line 48, in data "newrelic_entity" "entity":
1365 | 48: data "newrelic_entity" "entity" {

**Comment by MAN98** [comment] 2021-01-13 19:24
Seems to happen even if I use the later NR Provider version of 2.14.1

**Comment by zlesnr** [comment] 2021-01-13 19:34
Oh ouch.  Maybe the API changed underneath us.  I'll check on that.

**Comment by zlesnr** [comment] 2021-01-13 20:00
Is this happening consistently?  Can I see more detail for the `newrelic_entity` resource please?

**Comment by zlesnr** [comment] 2021-01-13 20:07
Also, can you confirm the version.  I just checked, and the `v2.7.1` of the provider wouldn't have included the `nrtime.Minutes` type yet.

**Comment by MAN98** [comment] 2021-01-13 21:08
@zlesnr - Yes it is happening consistently since today. I just re-ran our CI and still getting the same errors. Here's how we are using the newrelic_entity resource in our code:
`#entity tags (replaces synthetic labels)
data "newrelic_entity" "entity" {
  name = var.name
}

resource "newrelic_entity_tags" "tags" {
  guid = data.newrelic_entity.entity.guid

  dynamic "tag" {
    for_each = var.tags
    content {
      key    = tag.key
      values = list(tag.value)
    }
  }
}`

**Comment by MAN98** [comment] 2021-01-13 21:11
> Also, can you confirm the version. I just checked, and the `v2.7.1` of the provider wouldn't have included the `nrtime.Minutes` type yet.

@zlesnr - yep that's the NR Provider version we are using in our repo. But even using the latest version 2.14.1 still gets the same error

**Comment by zlesnr** [comment] 2021-01-14 16:53
Okay, synthetics specific was my expectation also.  I'll try to get a reproduction of this today or tomorrow and get back to you.

**Comment by zlesnr** [comment] 2021-01-14 18:38
This is also reproducible with `newrelic entity search --name WebPortal`, where `WebPortal` is our favorite demo app.

**Comment by zlesnr** [comment] 2021-01-14 19:14
This should be fixed in `v0.55.5`.  I'll work this through the CLI and Terraform next.

**Comment by zlesnr** [comment] 2021-01-14 19:15
Thank you for reporting the issue.  This was a lack of test coverage on our part, and not due to a change in the API.

**Closed** 2021-01-14 19:15 UTC

**Comment by MAN98** [comment] 2021-01-14 19:19
Thank you @zlesnr
